# Generated by Django 4.2.3 on 2023-07-06 12:51

import agent_v.users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", agent_v.users.models.UserManager()),
            ],
        ),
    ]
