# Generated by Django 4.2.3 on 2023-07-09 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepresentativeCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=15, unique=True)),
                ("capacity", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("descriptions", models.TextField()),
                (
                    "used_by",
                    models.ManyToManyField(blank=True, related_name="user_rcodes", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
