# Generated by Django 4.2.3 on 2023-08-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_representativecode_plan_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representativecode",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("cus", "custom"),
                    ("def", "default"),
                    ("one", "one"),
                    ("two", "two"),
                    ("three", "three"),
                    ("four", "four"),
                ],
                default="def",
                max_length=15,
            ),
        ),
    ]
