# Generated by Django 4.2.3 on 2023-07-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hiddify", "0002_alter_hprofile_hiddi_id_alter_hprofile_hiddi_uuid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.CharField()),
                ("name", models.CharField()),
                ("mode", models.CharField()),
                ("can_add_admin", models.BooleanField()),
                ("max_users", models.IntegerField()),
                ("max_active_users", models.IntegerField()),
                ("comment", models.CharField(blank=True, null=True)),
                ("telegram_id", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "admin_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_id", models.CharField()),
            ],
            options={
                "db_table": "child",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DailyUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(blank=True, null=True)),
                ("usage", models.BigIntegerField()),
                ("online", models.IntegerField()),
            ],
            options={
                "db_table": "daily_usage",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField()),
                ("alias", models.CharField(blank=True, null=True)),
                ("sub_link_only", models.BooleanField()),
                ("mode", models.CharField()),
                ("cdn_ip", models.TextField(blank=True, null=True)),
                ("grpc", models.BooleanField(blank=True, null=True)),
                ("servernames", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "domain",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HiddiUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.CharField()),
                ("name", models.CharField()),
                ("last_online", models.DateTimeField()),
                ("expiry_time", models.DateField(blank=True, null=True)),
                ("usage_limit_gb", models.TextField(db_column="usage_limit_GB")),
                ("package_days", models.IntegerField()),
                ("mode", models.CharField()),
                ("monthly", models.BooleanField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("current_usage_gb", models.TextField(db_column="current_usage_GB")),
                ("last_reset_time", models.DateField(blank=True, null=True)),
                ("comment", models.CharField(blank=True, null=True)),
                ("telegram_id", models.CharField(blank=True, null=True)),
                ("max_ips", models.IntegerField()),
                ("enable", models.BooleanField()),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ParentDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField()),
                ("alias", models.CharField()),
            ],
            options={
                "db_table": "parent_domain",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Proxy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField()),
                ("enable", models.BooleanField()),
                ("proto", models.CharField()),
                ("l3", models.CharField()),
                ("transport", models.CharField()),
                ("cdn", models.CharField()),
            ],
            options={
                "db_table": "proxy",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_online", models.DateTimeField()),
                ("current_usage_gb", models.TextField(db_column="current_usage_GB")),
                ("connected_ips", models.CharField()),
            ],
            options={
                "db_table": "user_detail",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BoolConfig",
            fields=[
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="hiddify.child",
                    ),
                ),
                ("key", models.CharField()),
                ("value", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "bool_config",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShowDomain",
            fields=[
                (
                    "domain",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="hiddify.domain",
                    ),
                ),
            ],
            options={
                "db_table": "show_domain",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ShowDomainParent",
            fields=[
                (
                    "domain",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="hiddify.parentdomain",
                    ),
                ),
            ],
            options={
                "db_table": "show_domain_parent",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StrConfig",
            fields=[
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="hiddify.child",
                    ),
                ),
                ("key", models.CharField()),
                ("value", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "str_config",
                "managed": False,
            },
        ),
    ]
