# Generated by Django 4.2.3 on 2023-07-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="volume",
            field=models.PositiveIntegerField(default=1, verbose_name="حجم (گیگابایت)"),
            preserve_default=False,
        ),
    ]
