# Generated by Django 4.2.3 on 2023-07-08 21:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("seller", "0002_plan_volume"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardToCardGate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "card_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.MinLengthValidator(16),
                            django.core.validators.RegexValidator(
                                re.compile("^-?\\d+\\Z"), code="invalid", message="Enter a valid integer."
                            ),
                        ],
                    ),
                ),
                ("cart_info", models.CharField(max_length=255)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_ctcgates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
