# Generated by Django 4.2.3 on 2023-07-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0003_cardtocardgate"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
