# Generated by Django 4.2.3 on 2023-07-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("seller", "0006_plan_plan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_one_time",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="payment",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_payments",
                to="seller.plan",
                verbose_name="پلن",
            ),
        ),
    ]
